# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: demarxes
  CLOUD_SQL_PASSWORD: dtothemarxes
  CLOUD_SQL_DATABASE_NAME: journalDB
  CLOUD_SQL_CONNECTION_NAME: adedotunalausa-website:us-central1:my-journal-sql
# [END gae_python37_cloudsql_config]
